data: 
  data_dir: /hpcfs/users/a1768536/AGPF/gnn4pions/ML_TREE_DATA/test_files/
  cell_geo_file: /hpcfs/users/a1768536/AGPF/gnn4pions/ML_TREE_DATA/cell_geo.root
  num_train_files: 1
  num_val_files: 1
  batch_size: 1024
  shuffle: False
  num_procs: 32
  preprocess: True
  output_dir: /hpcfs/users/a1768536/AGPF/gnn4pions/proper_run/
  already_preprocessed: False
  class_0: pi0
  class_1: piplus 
model:
  block_type: graphnet
  concat_input: true
  edge_block_opt: {use_edges: true, use_globals: true, use_receiver_nodes: true, use_sender_nodes: true}
  global_block_opt: {use_edges: false, use_globals: true, use_nodes: true}
  latent_size: 64
  node_block_opt: {use_globals: true, use_nodes: true, use_received_edges: true, use_sent_edges: false}
  num_blocks: 4
  num_layers: 4
  reducer: mean
training: 
  alpha: 0.5
  epochs: 50
  gpu: 1
  learning_rate: 0.01
  log_freq: 100
  save_dir: results/piplus_pi0_03_12_24_v09/ 
