data: 
  data_dir: /clusterfs/ml4hep/mpettee/ml4pions/data/onetrack_multicluster/
  cell_geo_file: /clusterfs/ml4hep/mpettee/ml4pions/data/cell_geo.root
  num_train_files: 10
  num_val_files: 10
  batch_size: 1024
  shuffle: False
  num_procs: 32
  preprocess: True
  output_dir: /clusterfs/ml4hep/mpettee/ml4pions/data/onetrack_multicluster/preprocessed/
  already_preprocessed: False
model:
  block_type: deepsets
  concat_input: true
  edge_block_opt: {use_edges: true, use_globals: true, use_receiver_nodes: true, use_sender_nodes: true}
  global_block_opt: {use_edges: false, use_globals: true, use_nodes: true}
  latent_size: 64
  node_block_opt: {use_globals: true, use_nodes: true, use_received_edges: true, use_sent_edges: false}
  num_blocks: 1
  num_layers: 3
  reducer: mean
training: 
  alpha: .75 
  epochs: 10
  gpu: 2
  learning_rate: 0.001
  log_freq: 100
  save_dir: results/onetrack_multicluster/ 
