data: 
  data_dir: /usr/workspace/hip/ML4Jets/regression_images/graphs.v01-45-gaa27bcb/onetrack_multicluster/pion_files/
  num_train_files: 350
  num_val_files: 50
  batch_size: 2048
  n_clusters: -1
  shuffle: False
  num_procs: 32
  preprocess: True
  output_dir: /p/vast1/karande1/heavyIon/data/preprocessed_data/gn4pions/track_noCells_nClusters_deepset/
  already_preprocessed: False
model:
  block_type: deepsets
  concat_input: False
  latent_size: 64
  num_blocks: 1
  num_layers: 3
  reducer: sum
training: 
  epochs: 100
  gpu: 3
  learning_rate: 0.001
  log_freq: 100
  save_dir: results/onetrack_multicluster/ 
