data: 
  data_dir: /usr/workspace/hip/ML4Jets/regression_images/graphs.v01-45-gaa27bcb/onetrack_multicluster/pion_files/
  num_train_files: 200
  num_val_files: 50
  batch_size: 1024
  n_clusters: -1
  shuffle: False
  num_procs: 32
  preprocess: True
  output_dir: /p/vast1/karande1/heavyIon/data/preprocessed_data/gn4pions/track_noCells_nClusters/
  already_preprocessed: False
model:
  block_type: graphnet
  concat_input: False
  edge_block_opt: {use_edges: true, use_globals: true, use_receiver_nodes: true, use_sender_nodes: true}
  global_block_opt: {use_edges: false, use_globals: true, use_nodes: true}
  latent_size: 32
  node_block_opt: {use_globals: true, use_nodes: true, use_received_edges: true, use_sent_edges: false}
  num_blocks: 1
  num_layers: 2
  reducer: mean
training: 
  epochs: 30
  gpu: 2
  learning_rate: 0.001
  log_freq: 100
  save_dir: results/onetrack_multicluster/ 
