# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_data.ipynb (unless otherwise specified).

__all__ = ['scales', 'node_means', 'node_stds']

# Cell
import numpy as np
import glob
import os
import uproot as ur
import time
from multiprocessing import Process, Queue, set_start_method
import compress_pickle as pickle
from scipy.stats import circmean
import random
import itertools
import tensorflow as tf

import matplotlib.pyplot as plt # optional
plt.rcParams.update({
    "text.usetex": True,
    "font.family": "serif",
    "font.serif": ["Palatino"],
})

import pandas as pd

# Cell

scales = {
     'track_pt_mean': 1.633278727,
     'track_pt_std': 0.8481947183,
     'track_z0_mean': 0.08022017,
     'track_z0_std': 42.53320004,
     'track_eta_mean': -0.00563187,
     'track_eta_std': 1.35242735,
     'track_phi_mean': 0.00206431,
     'track_phi_std': 1.81240248,
     'truth_part_e_mean': 1.92469358,
     'truth_part_e_std': 0.8289864,
     'cluster_cell_e_mean': -1.0121697,
     'cluster_cell_e_std': 0.818357,
     'cluster_e_mean': 0.89923394,
     'cluster_e_std': 1.0585934,
     'cluster_eta_mean': 0.016195267,
     'cluster_eta_std': 1.3400925,
     'cluster_phi_mean': 0.0050816955,
     'cluster_phi_std': 1.8100655,
     'cell_geo_sampling_mean': 3.8827391420197177,
     'cell_geo_sampling_std': 3.9588233603576204,
     'cell_geo_eta_mean': 0.0005979097,
     'cell_geo_eta_std': 1.4709069,
     'cell_geo_phi_mean': -2.8938382e-05,
     'cell_geo_phi_std': 1.813651,
     'cell_geo_rPerp_mean': 1478.9285,
     'cell_geo_rPerp_std': 434.60815,
     'cell_geo_deta_mean': 0.026611786,
     'cell_geo_deta_std': 0.03396141,
     'cell_geo_dphi_mean': 0.068693615,
     'cell_geo_dphi_std': 0.038586758}

node_means = [
    scales["cluster_cell_e_mean"],
    scales["cell_geo_sampling_mean"],
    scales["cell_geo_eta_mean"],
    scales["cell_geo_phi_mean"],
    scales["cell_geo_rPerp_mean"],
    scales["cell_geo_deta_mean"],
    scales["cell_geo_dphi_mean"],
]

node_stds = [
    scales["cluster_cell_e_std"],
    scales["cell_geo_sampling_std"],
    scales["cell_geo_eta_std"],
    scales["cell_geo_phi_std"],
    scales["cell_geo_rPerp_std"],
    scales["cell_geo_deta_std"],
    scales["cell_geo_dphi_std"],
]