# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_utils.ipynb (unless otherwise specified).

__all__ = ['convert_to_tuple']

# Cell
import numpy as np
import tensorflow as tf
from graph_nets.graphs import GraphsTuple

# Cell
def convert_to_tuple(graphs):
    nodes = []
    edges = []
    global_nodes = []
    senders = []
    receivers = []
    n_node = []
    n_edge = []
    offset = 0

    for graph in graphs:
        nodes.append(graph['nodes'])
        edges.append(graph['edges'])
        global_nodes.append([graph['globals']])
        senders.append(graph['senders'] + offset)
        receivers.append(graph['receivers'] + offset)
        n_node.append(graph['nodes'].shape[:1])
        n_edge.append(graph['edges'].shape[:1])

        offset += len(graph['nodes'])

    nodes = tf.convert_to_tensor(np.concatenate(nodes))
    edges = tf.convert_to_tensor(np.concatenate(edges))
    global_nodes = tf.convert_to_tensor(np.concatenate(global_nodes))
    senders = tf.convert_to_tensor(np.concatenate(senders))
    receivers = tf.convert_to_tensor(np.concatenate(receivers))
    n_node = tf.convert_to_tensor(np.concatenate(n_node))
    n_edge = tf.convert_to_tensor(np.concatenate(n_edge))

    graph = GraphsTuple(
            nodes=nodes,
            edges=edges,
            globals=global_nodes,
            senders=senders,
            receivers=receivers,
            n_node=n_node,
            n_edge=n_edge
        )

    return graph