# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"scales": "00_data.ipynb",
         "node_means": "00_data.ipynb",
         "node_stds": "00_data.ipynb",
         "GraphDataGenerator": "00_data.ipynb",
         "TrackGraphDataGenerator": "00_data_noCalirometer.ipynb",
         "TrackDataGenerator": "00_data_noCalirometer.ipynb",
         "CaloTrackGraphDataGenerator": "00_data_wTracks.ipynb",
         "MultiCaloTrackDataGenerator": "00_data_wTracks_MultiCluster.ipynb",
         "make_mlp_model": "01_models.ipynb",
         "MLPGraphIndependent": "01_models.ipynb",
         "MLPGraphNetwork": "01_models.ipynb",
         "MLPDeepSets": "01_models.ipynb",
         "MultiOutWeightedRegressModel": "01_models.ipynb",
         "MultiOutBlockModel": "01_models.ipynb",
         "SimpleGraphModel": "01_models.ipynb",
         "convert_to_tuple": "02_utils.ipynb"}

modules = ["modules/data.py",
           "modules/data_tracks.py",
           "modules/data_trackCalo.py",
           "modules/data_trackMultiCalo.py",
           "modules/models.py",
           "modules/utils.py"]

doc_url = "https://atlas-calo-ml.github.io/gn4pions/"

git_url = "https://github.com/atlas-calo-ml/gn4pions/tree/master/"

def custom_doc_links(name): return None
